### PR TITLE
Exporter export sources

### LINKED ISSUE #169: ActiveRecord::InvalidForeignKey in Bulkrax::ExportersController#create
Adding a new / updating an existing `Entry` with an `importerexporter_type` of `Bulkrax::Exporter` isn't correctly searching the `bulkrax_exporters` table for the `importerexporter_id` (during `find_or_create!`), it's only searching the `bulkrax_importers` table. 

**Full trace:** 

```ruby
PG::ForeignKeyViolation: ERROR: insert or update on table "bulkrax_entries" violates foreign key constraint "fk_rails_4b1551b945" DETAIL: Key (importerexporter_id)=(3) is not present in table "bulkrax_importers". : INSERT INTO "bulkrax_entries" ("identifier", "type", "importerexporter_id", "created_at", "updated_at", "importerexporter_type") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"
```

**Proposed fix:** Remove the foreign key from the `bulkrax_entries` table that references the `bulkrax_importers`. 

Encountered error when trying to run an `Exporter` with an `export_source` that already has an been run through a different `Exporter`.

### PR DESCRIPTION
**Pull request by geekscruff**
**Work completed:** 

- add javascript for dynamic selection of export source
- add work_type to export form
- add a method to the parser to create from work type
- added i18n support for export#edit form
- added collection autosuggest
- store id of collection from autosuggest
- tests
- some additonal js stuff (see comments in exporter.js)
- ensure limit works
- ensure form fields are populated correctly on edit
- input styling 

Once merged, should also resolve #169, #170, and #171

### CODE REVIEW

File: app/parsers/bulkrax/application_parser.rb [hunk 1]
```diff
@@ -157,6 +157,14 @@ def exporter?
       importerexporter.is_a?(Bulkrax::Exporter)
     end
 
+    # @param limit [Integer] limit set on the importerexporter
+    # @param index [Integer] index of current iteration
+    # @return [boolean]
+    def limit_reached?(limit, index)
```
Comment (geekscruff) [inline app/parsers/bulkrax/application_parser.rb]: 👍 👍 👍
